"""Shared constants for the production planning MVP."""

ORDER_STATUS_NEW = "Новый"
ORDER_STATUS_PLANNED = "Запланирован"
ORDER_STATUS_CONFLICT = "Конфликт планирования"
ORDER_STATUS_CANCELLED = "Отменён"

ORDER_STATUSES = (
    ORDER_STATUS_NEW,
    ORDER_STATUS_PLANNED,
    ORDER_STATUS_CONFLICT,
    ORDER_STATUS_CANCELLED,
)

MANUAL_ORDER_STATUSES = (
    ORDER_STATUS_NEW,
    ORDER_STATUS_CANCELLED,
)

CALCULATED_ORDER_STATUSES = (
    ORDER_STATUS_PLANNED,
    ORDER_STATUS_CONFLICT,
)

PLANNABLE_ORDER_STATUSES = {
    ORDER_STATUS_NEW,
    ORDER_STATUS_PLANNED,
    ORDER_STATUS_CONFLICT,
}

NON_PLANNABLE_ORDER_STATUSES = {
    ORDER_STATUS_CANCELLED,
}
