"""Shared constants for the production planning MVP."""

ORDER_STATUS_NEW = "Новый"
ORDER_STATUS_PLANNED = "Запланирован"
ORDER_STATUS_CANCELLED = "Отменён"

ORDER_STATUSES = (
    ORDER_STATUS_NEW,
    ORDER_STATUS_PLANNED,
    ORDER_STATUS_CANCELLED,
)

MANUAL_ORDER_STATUSES = (
    ORDER_STATUS_NEW,
    ORDER_STATUS_CANCELLED,
)

CALCULATED_ORDER_STATUSES = (ORDER_STATUS_PLANNED,)

PLANNABLE_ORDER_STATUSES = {
    ORDER_STATUS_NEW,
    ORDER_STATUS_PLANNED,
}

NON_PLANNABLE_ORDER_STATUSES = {
    ORDER_STATUS_CANCELLED,
}
